# This is the Dynamic Workflow configuration file.
#
# This file contains all the import information needed to run Dynamic Workflows.
# Please make sure that all your information is correct.

# This is the port that the express server should listen on if it is not provided by process.env.PORT
port: 80

# This is the server information needed to point the application to your Sign Console.
server:
  # The host address to your Sign Console.
  host: "https://api.na1.adobesign.com"

  # DO NOT CHANGE THE FOLLOW TWO CONFIGURATION.
  # This is the endpoint
  endpoint: "/api/rest/v5"

# This is the enterprise setting to get access to your Sign Console.
enterprise:
  # This is your integration key for Adobe Sign. This key
  # is needed to get access to perform synchronization between Admin
  # Console and Adobe Sign.
  integration: 3AAABLblqZhDeBs100ch3YwM6EP2EpDmC0CpHTMAuLlzb_WuM73zEDkwhdKUNpO7NcSfG4BipCNVtWHevjIWmnJLsmNkWLI5W

# This is the feature configuration.
features:
   # This feature will allow first signer to be redirected to the ready to complete document immediately
  # yes to redirect
  # no to email
  sign_now: yes
  sign_now_retries: 60

  # This feature will allow workflows to be filtered to only show the workflows desired.
  # Should be strings in list below
  # List empty: all workflows shown in dropdown list
  allowed_workflows:
    # - "{workflow name}"
    # - "{workflow id}"

  #This feature will navigate the user to a workflow via a URL path
  # yes to allow deeplinking
  # no to deny deeplinking
  deep_links: yes

  #This feature disable workflow dropdown selector
  # yes to disable
  # no to enable
  disable_index: no

  # This feature will inject CSS rules into the tool.
  # Use a minified CSS string.
  # Rules are delimited w/ a `;` semicolon
  # If a rule is not overriding, you might need to use the `!important` hack.
  css_override: "#agreement_section, #message_section {display: none !important}"
  # css_override: "#main-options {display:none}"  # Hide Options Section
  # css_override: "#main-options {display:none}; #recipient_submit_button {background-color: red !important}"  # Hide Options Section

  # Disable extra options
  # this setting disables the grey sidebar that enables senders to control reminders
  disable_extra_options: yes

  # This feature will allow the userId or email of API caller using the account or group token in the
  # format userid:{userId} OR email:{email}. If it is not specified, then the caller is inferred from the token.
  x-api-user: ""

  # This feature will hide predefined recipients within your workflow.
  hide_predefined: yes

  # HIDE PREDEFINED RECIPIENTS WITH TARGET WORKFLOWS
  ## Add workflow names under hide_workflow_list such as " - Workflow name"
  hide_workflow_list:
    # - "{workflow name}"
    # - "{workflow id}"

  # Hide predefined cc recipients within your workflow
  hide_cc: yes

  # Hide predefined cc recipients with target workflows
  ## Add workflow names under hide_cc_workflow_list such as " - Workflow name"
  hide_cc_workflow_list:
    # - "{workflow name}"
    # - "{workflow id}"

  # Email regex to be used to restrict emails used during signing
  email_regex: ^\w+([\.\+-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$

  # Error to display if there is an error with the email validation
  email_error_message: "There is a problem with your email address."
